<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title>User</title>
</head>
<body>
<table>
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>${user.id}</td>
        <td>${user.firstName}</td>
        <td>${user.lastName}</td>
    </tr>
    </tbody>
</table>
</body>
</html>
